version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: travel-world-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: travel-world
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
