spring:
  application:
    name: travel

  profiles:
    active: dev
    include: custom

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    user: postgres
    password: 123123
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0

  mail:
    host: smtp.gmail.com
    port: 587
    username: nam2023.11.07@gmail.com
    password: Khong@123145667899
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
    protocol: smtp

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
    tags-sorter: alpha
    operations-sorter: method
  show-actuator: true

server:
  port: 8080
  servlet:
    context-path: /travel-app/api/v1.0

logging:
  level:
    org.springframework.security: DEBUG
    org.mybatis: DEBUG
    app.travel: DEBUG

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
