spring:
  application:
    name: travel

  profiles:
    active: dev
    include: custom

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: true

  flyway:
    user: postgres
    password: 123123
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0

  mail:
    host: smtp.gmail.com
    port: 587
    username: nam2023.11.07@gmail.com
    password: vhtugesokjfiqmjk
    protocol: smtp
    properties:
      debug: true
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          socketFactory:
            fallback: true
          connectiontimeout: 5000
          writetimeout: 5000
          timeout: 5000

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
    tags-sorter: alpha
    operations-sorter: method
  show-actuator: true

server:
  port: 8080
  servlet:
    context-path: /travel-app/api/v${app.openapi.info.version}

logging:
  level:
    org.springframework.security: DEBUG
    org.mybatis: DEBUG
    app.travel: DEBUG

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
