app:
  path:
    backend:
      refresh-token: /auth/refresh-token
    frontend:
      signup-confirm: /signup/confirm

  jwt:
    secret-key: d]"erpMJ-hf-+!K|8jaw~tXXtOM{1fxRSoggAm-1I0YzY4jdeB>]r6x{5YN'M=s|Pp>JVO*zU~fU'`S
    access-duration-time: 900000
    refresh-duration-time: 604800000
    issuer: travel-app

  server:
    secret-key:
      crypto:
        aes-gcm: mCHpWbuvLwsDa3ZxW8j9H9S17grMFEZA

  mail:
    templates:
      signup-confirm: mail-signup-confirm-template.html
    subjects:
      signup-confirm: Confirm your register with Travel App.
